-- sql/schema.sql (CORREGIDO)

-- Tabla de usuarios (perfiles públicos)
-- Esta tabla se vincula a los usuarios de Supabase Auth a través del ID.
CREATE TABLE usuarios (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username VARCHAR(50) UNIQUE NOT NULL,
  nivel_gamer VARCHAR(20) DEFAULT 'Beginner' CHECK (nivel_gamer IN ('Beginner', 'Casual', 'Avid', 'Hardcore')),
  fecha_registro TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Tabla de géneros
CREATE TABLE generos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(50) UNIQUE NOT NULL,
  descripcion TEXT
);

-- Tabla de plataformas
CREATE TABLE plataformas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(50) UNIQUE NOT NULL,
  fabricante VARCHAR(50)
);

-- Tabla de videojuegos
CREATE TABLE videojuegos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(200) NOT NULL,
  desarrollador VARCHAR(100),
  año_lanzamiento INTEGER,
  precio DECIMAL(10, 2) DEFAULT 0.00,
  rating DECIMAL(3, 2) DEFAULT 0.00,
  descripcion TEXT
);

-- Relaciones (sin cambios)
CREATE TABLE videojuego_generos (
  videojuego_id BIGINT REFERENCES videojuegos(id) ON DELETE CASCADE,
  genero_id BIGINT REFERENCES generos(id) ON DELETE CASCADE,
  PRIMARY KEY (videojuego_id, genero_id)
);

CREATE TABLE videojuego_plataformas (
  videojuego_id BIGINT REFERENCES videojuegos(id) ON DELETE CASCADE,
  plataforma_id BIGINT REFERENCES plataformas(id) ON DELETE CASCADE,
  PRIMARY KEY (videojuego_id, plataforma_id)
);

-- Tabla de reseñas
-- El campo usuario_id ahora debe ser de tipo UUID para coincidir con el id de auth.users
CREATE TABLE reseñas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  videojuego_id BIGINT REFERENCES videojuegos(id) ON DELETE CASCADE NOT NULL,
  puntuacion INTEGER NOT NULL CHECK (puntuacion BETWEEN 1 AND 10),
  comentario TEXT,
  fecha_reseña TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  UNIQUE(usuario_id, videojuego_id)
);